version: "3"
services:
  frontend:
    image: frappe/erpnext:v15.77.0
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend-e0w8kcggcosk8c8g08s4g80k-120521016541

      FRAPPE_SITE_NAME_HEADER: https://test2.erpnext.omega-eg.io
      SOCKETIO: websocket-e0w8kcggcosk8c8g08s4g80k-120521171569

      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8082:8080"

volumes:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
